// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { BuyMeACoffee$Type } from "./BuyMeACoffee";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BuyMeACoffee"]: BuyMeACoffee$Type;
    ["contracts/BuyMeACoffee.sol:BuyMeACoffee"]: BuyMeACoffee$Type;
  }
}
